{"name": "test_url_wrong", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'http://www.blazedemo.com/' == 'http://www.b....com/ggfjgfjg'\n  - http://www.blazedemo.com/ggfjgfjg\n  ?                          --------\n  + http://www.blazedemo.com/", "trace": "self = <test_BlazeDemoAutomation.Test object at 0x04D56268>, dataload = ['http://www.blazedemo.com/', 'niharika']\n\n    @pytest.mark.failedtestcase\n    def test_url_wrong(self, dataload):  # refers to the dataload fixture\n>       assert self.driver.current_url == \"http://www.blazedemo.com/ggfjgfjg\"\nE       AssertionError: assert 'http://www.blazedemo.com/' == 'http://www.b....com/ggfjgfjg'\nE         - http://www.blazedemo.com/ggfjgfjg\nE         ?                          --------\nE         + http://www.blazedemo.com/\n\ntest_BlazeDemoAutomation.py:23: AssertionError"}, "start": 1588835810545, "stop": 1588835810561, "uuid": "728957c7-a78b-4ab5-9083-f673051ba54b", "historyId": "6582c33b0010b179489111418c1f35c0", "testCaseId": "92faaeca2681dcb17b4c7105e1ac1450", "fullName": "test_BlazeDemoAutomation.Test#test_url_wrong", "labels": [{"name": "tag", "value": "failedtestcase"}, {"name": "suite", "value": "test_BlazeDemoAutomation"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "USHYDNIHARGUP1"}, {"name": "thread", "value": "19208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_BlazeDemoAutomation"}]}